imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap
framework:
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id: ~
        save_path: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    encryption: ssl
    spool: { type: memory }

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:  [admin]
        sonata.user.block.menu:  # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes

sonata_user:
    manager_type: orm

sonata_admin:
    show_mosaic_button: false
    security:
        handler: sonata.admin.security.handler.acl
        information:
            GUEST:    [VIEW, LIST]
            ADMIN:    [MASTER]
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

fos_user:
    db_driver:  orm
    firewall_name:  main
    user_class:  Application\Sonata\UserBundle\Entity\User
    from_email:
        address: '%mailer_user%'
        sender_name: Anthony
    group:
        group_class:  Application\Sonata\UserBundle\Entity\Group
    service:
        user_manager: sonata.user.orm.user_manager

white_october_breadcrumbs: ~

vich_uploader:
    db_driver: orm
    mappings:
        kuhni:
            uri_prefix:         /web/upload/kuhni/kitchens
            upload_destination: %kernel.root_dir%/../web/upload/kuhni/kitchens
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        kuhni_style:
            uri_prefix:         /web/upload/kuhni/style
            upload_destination: %kernel.root_dir%/../web/upload/kuhni/style
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        kuhni_material:
            uri_prefix:         /web/upload/kuhni/material
            upload_destination: %kernel.root_dir%/../web/upload/kuhni/material
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        kuhni_config:
            uri_prefix:         /web/upload/kuhni/config
            upload_destination: %kernel.root_dir%/../web/upload/kuhni/config
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        kuhni_fasad:
            uri_prefix:         /web/upload/kuhni/fasad
            upload_destination: %kernel.root_dir%/../web/upload/kuhni/fasad
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        catalog_image:
            uri_prefix:         /web/upload/catalog
            upload_destination: %kernel.root_dir%/../web/upload/catalog
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        kuhni_zakazy_cost_project:
            uri_prefix:         /web/upload/zakazy/costproject
            upload_destination: %kernel.root_dir%/../web/upload/zakazy/costproject
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        kuhni_zakazy_freedesign:
            uri_prefix:         /web/upload/zakazy/freedesign
            upload_destination: %kernel.root_dir%/../web/upload/zakazy/freedesign
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true