kuhni:
    resource: "@KuhniBundle/Resources/config/routing.yml"
    prefix:   /

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

sonata_user:
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
  prefix: /admin

admin:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /admin

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin