homepage:
    path:     /
    defaults: { _controller: KuhniBundle:Homepage:index }
get:
    resource: "@KuhniBundle/Controller/KuhniCatalogController.php"
    type:     annotation
callback:
    path:  /callback
    defaults: { _controller: "KuhniBundle:CallBack:index" }
    requirements:
        methods:  GET|POST