homepage:
    path:     /
    defaults: { _controller: KuhniBundle:Homepage:index }
get:
    resource: "@KuhniBundle/Controller/KuhniCatalogController.php"
    type:     annotation
    requirements:
        methods:  GET|POST
callback:
    path:  /callback
    defaults: { _controller: "KuhniBundle:CallBack:index" }
    requirements:
        methods:  GET|POST
requestcall:
    path:  /requestcall
    defaults: { _controller: "KuhniBundle:RequestCall:index" }
    requirements:
        methods:  GET|POST
freeproject:
    path:  /freeproject
    defaults: { _controller: "KuhniBundle:freeDesignProject:index" }
    requirements:
        methods:  GET|POST
freedesignshag:
    path:  /freedesignshag
    defaults: { _controller: "KuhniBundle:DesignProjectShag:index" }
    requirements:
        methods:  GET|POST
zayavkarazmer:
    path:  /zayavkarazmer
    defaults: { _controller: "KuhniBundle:zayavkaRazmer:index" }
    requirements:
        methods:  GET|POST
costproject:
    path:  /costproject
    defaults: { _controller: "KuhniBundle:CostProject:index" }
    requirements:
        methods:  GET|POST
designerathome:
    path:  /designerathome
    defaults: { _controller: "KuhniBundle:DesignerAtHome:index" }
    requirements:
        methods:  GET|POST
review:
    path:  /review
    defaults: { _controller: "KuhniBundle:Review:index" }
    requirements:
        methods:  GET|POST
reviews:
    path:  /reviews
    defaults: { _controller: "KuhniBundle:Reviews:index" }
    requirements:
        methods:  GET|POST
about:
    path:  /about
    defaults: { _controller: "KuhniBundle:About:index" }
    requirements:
        methods:  GET|POST
promo:
    path:  /promo
    defaults: { _controller: "KuhniBundle:Promo:index" }
    requirements:
        methods:  GET|POST
promo_order:
    path:  /promo_order
    defaults: { _controller: "KuhniBundle:Promo:order" }
    requirements:
        methods:  GET|POST
privacy:
    path:  /privacy
    defaults: { _controller: "KuhniBundle:Privacy:index" }
    requirements:
        methods:  GET|POST
zovzakaz:
    path:  /zovzakaz
    defaults: { _controller: "KuhniBundle:ZovZakaz:index" }
    requirements:
        methods:  GET|POST
newzovzakaz:
    path:  /newzovzakaz
    defaults: { _controller: "KuhniBundle:ZovZakaz:newZakaz" }
    requirements:
        methods:  GET|POST
track:
    path:  /track
    defaults: { _controller: "KuhniBundle:ZovZakaz:track" }
    requirements:
        methods:  GET|POST
trackCheck:
    path:  /trackCheck
    defaults: { _controller: "KuhniBundle:ZovZakaz:trackCheck" }
    requirements:
        methods:  GET|POST
salon-all:
    path:  /salon
    defaults: { _controller: "KuhniBundle:Profiler:index" }
    requirements:
        methods:  GET|POST
salon-address:
    path:  /salon/{slugAddress}
    defaults: { _controller: "KuhniBundle:Profiler:searchAddress" }
    requirements:
        methods:  GET|POST
salon-profile:
    path:  /salon/{slugAddress}/{slug}/
    defaults: { _controller: "KuhniBundle:Profiler:show" }
    requirements:
        methods:  GET|POST
newlike:
    path:  /newlike
    defaults: { _controller: "KuhniBundle:Like:index" }
    requirements:
        methods:  GET|POST
newlikeproject:
    path:  /newlikeproject
    defaults: { _controller: "KuhniBundle:Profiler:like" }
    requirements:
        methods:  GET|POST
all-projects:
    path:  /projects/
    defaults: { _controller: "KuhniBundle:Project:allProjects" }
    requirements:
        methods:  GET|POST
projects-filter:
    path:  /projects/{filter}/
    defaults: { _controller: "KuhniBundle:Project:projectsFilter" }
    requirements:
        methods:  GET|POST
project:
    path:  /projects/{filter}/{nameproject}
    defaults: { _controller: "KuhniBundle:Project:project" }
    requirements:
        methods:  GET|POST