services:
  app.admin.orderitems:
    class: Kuhni\Bundle\Admin\KuhniStyleAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Кухни", label: "Стили кухонь" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\KuhniStyle
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true