services:
#         Каталог
  app.admin.catalog:
    class: Kuhni\Bundle\Admin\CatalogAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Каталог", label: "Каталог" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\Catalog
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
  app.admin.kuhni:
    class: Kuhni\Bundle\Admin\KuhniAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Каталог", label: "Кухни" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\Kuhni
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
#         Кухни
  app.admin.kuhni.keys:
    class: Kuhni\Bundle\Admin\KuhniKeysAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Кухни", label: "Ключи" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\KuhniKeys
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
  app.admin.kuhni.images:
    class: Kuhni\Bundle\Admin\KuhniImagesAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Кухни", label: "Картинки кухонь" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\KuhniImages
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
#         Фасады
  app.admin.fasades.type:
    class: Kuhni\Bundle\Admin\FasadTypeAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Фасады", label: "Типы фасадов" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\FasadType
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
  app.admin.fasades.color:
    class: Kuhni\Bundle\Admin\FasadColorAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Фасады", label: "Цвета фасадов" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\FasadColor
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
#         Заказы
  app.admin.order.callback:
    class: Kuhni\Bundle\Admin\FormCallBackAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Заказы", label: "Обратный звонок" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\FormCallBack
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
  app.admin.order.designerAtHome:
    class: Kuhni\Bundle\Admin\FormDesignerAtHomeAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Заказы", label: "Дизайнер на дом" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\FormDesignerAtHome
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
  app.admin.order.requestCall:
    class: Kuhni\Bundle\Admin\FormRequestCallAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Заказы", label: "Заказы на звонок" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\FormRequestCall
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
  app.admin.order.zayavkaRazmer:
    class: Kuhni\Bundle\Admin\FormZayavkaRazmerAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Заказы", label: "Расчет размеров" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\FormZayavkaRazmer
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
  app.admin.order.freeDesignProject:
    class: Kuhni\Bundle\Admin\FormFreeDesignProjectAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Заказы", label: "Бесплатный дизайн-проект" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\FormFreeDesignProject
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
  app.admin.order.designProjectShag:
    class: Kuhni\Bundle\Admin\FormDesignProjectShagAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Заказы", label: "Пошаговая форма" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\FormDesignProjectShag
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
  app.admin.order.costProject:
    class: Kuhni\Bundle\Admin\FormCostProjectAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Заказы", label: "Расчет стоимости проекта" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\FormCostProject
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
  app.admin.order.reviews:
    class: Kuhni\Bundle\Admin\ReviewsAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Заказы", label: "Отзывы" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\Reviews
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
#slider homepage
  app.admin.slider.home:
    class: Kuhni\Bundle\Admin\HomeSliderImagesAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Настройки", label: "Картинки для слайдера" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\HomeSliderImages
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
#  Promo
  app.admin.promo:
    class: Kuhni\Bundle\Admin\FormPromoAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: Настройки , label: "Промо" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\Promo
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
#  Settings
  app.admin.salon:
    class: Kuhni\Bundle\Admin\SalonAdmin
    arguments: [~, Kuhni\Bundle\Entity\Salon, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Пользователи!!!!!", label: "Салоны" }
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
  app.admin.salon.salonimages:
    class: Kuhni\Bundle\Admin\SalonImagesAdmin
    arguments: [~, Kuhni\Bundle\Entity\SalonImages, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Пользователи!!!!!", label: "Картинки салонов" }
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true
  application_sonata_user.admin.user:
    class: Application\Sonata\UserBundle\Admin\UserAdmin
    arguments: [~, Application\Sonata\UserBundle\Entity\User, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Пользователи!!!!!", label: "Пользователи" }
    calls:
      - [ setTranslationDomain, [Application\Sonata\UserBundle]]
    public: true
  app.admin.settings:
    class: Kuhni\Bundle\Admin\SettingsAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: Настройки , label: "Настройки" }
    arguments:
      - ~
      - Kuhni\Bundle\Entity\Settings
      - ~
    calls:
      - [ setTranslationDomain, [Kuhni\Bundle]]
    public: true

  kuhnibundle.sitemap.kuhni_parameters:
      class: Kuhni\Bundle\Service\Sitemap\KuhniParametersProvider
      arguments: [@doctrine.orm.entity_manager]
  kuhnibundle.sitemap.kuhni_product:
      class: Kuhni\Bundle\Service\Sitemap\KuhniProductProvider
      arguments: [@doctrine.orm.entity_manager]