<?php

namespace Kuhni\Bundle\Repository;

/**
 * CallBackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallBackRepository extends \Doctrine\ORM\EntityRepository
{
}
