<?php

namespace Kuhni\Bundle\Repository;

/**
 * CostProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
