<?php

namespace Kuhni\Bundle\Repository;

/**
 * DesignProjectShagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesignProjectShagRepository extends \Doctrine\ORM\EntityRepository
{
}
