<?php

namespace Kuhni\Bundle\Repository;

/**
 * DesignerAtHomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesignerAtHomeRepository extends \Doctrine\ORM\EntityRepository
{
}
