<?php

namespace Kuhni\Bundle\Repository;

/**
 * FasadColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FasadColorRepository extends \Doctrine\ORM\EntityRepository
{
}
