<?php

namespace Kuhni\Bundle\Repository;

/**
 * FasadTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FasadTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
