<?php

namespace Kuhni\Bundle\Repository;

/**
 * FormPromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormPromoRepository extends \Doctrine\ORM\EntityRepository
{
}
