<?php

namespace Kuhni\Bundle\Repository;

/**
 * FormFreeDesignProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormFreeDesignProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
