<?php

namespace Kuhni\Bundle\Repository;

/**
 * FormDesignerAtHomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormDesignerAtHomeRepository extends \Doctrine\ORM\EntityRepository
{
}
