<?php

namespace Kuhni\Bundle\Repository;

/**
 * FormCostProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormCostProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
