<?php

namespace Kuhni\Bundle\Repository;

/**
 * FormRequestCallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormRequestCallRepository extends \Doctrine\ORM\EntityRepository
{
}
