<?php

namespace Kuhni\Bundle\Repository;

/**
 * FormZayavkaRazmerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormZayavkaRazmerRepository extends \Doctrine\ORM\EntityRepository
{
}
