<?php

namespace Kuhni\Bundle\Repository;

/**
 * FormDesignProjectShagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormDesignProjectShagRepository extends \Doctrine\ORM\EntityRepository
{
}
