<?php

namespace Kuhni\Bundle\Repository;

/**
 * freeDesignProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class freeDesignProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
