<?php

namespace Kuhni\Bundle\Repository;

/**
 * HomeSliderImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeSliderImagesRepository extends \Doctrine\ORM\EntityRepository
{
}