<?php

namespace Kuhni\Bundle\Repository;

/**
 * KuhniStyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuhniStyleRepository extends \Doctrine\ORM\EntityRepository
{
}
