<?php

namespace Kuhni\Bundle\Repository;

/**
 * KuhniGlassRepositoryextends
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuhniGlassRepository extends \Doctrine\ORM\EntityRepository
{
}
