<?php

namespace Kuhni\Bundle\Repository;

/**
 * KuhniShponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuhniShponRepository extends \Doctrine\ORM\EntityRepository
{
}
