<?php

namespace Kuhni\Bundle\Repository;

/**
 * KuhniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuhniRepository extends \Doctrine\ORM\EntityRepository
{
}
