<?php

namespace Kuhni\Bundle\Repository;

/**
 * KuhniMdfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuhniMdfRepository extends \Doctrine\ORM\EntityRepository
{
}
