<?php

namespace Kuhni\Bundle\Repository;

/**
 * KuhniMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuhniMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
