<?php

namespace Kuhni\Bundle\Repository;

/**
 * KuhniConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuhniConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
