<?php

namespace Kuhni\Bundle\Repository;

/**
 * KuhniColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuhniColorRepository extends \Doctrine\ORM\EntityRepository
{
}
