<?php

namespace Kuhni\Bundle\Repository;

/**
 * KuhniMassiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuhniMassiveRepository extends \Doctrine\ORM\EntityRepository
{
}
