<?php

namespace Kuhni\Bundle\Repository;

/**
 * KuhniImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuhniImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
