<?php

namespace Kuhni\Bundle\Repository;

/**
 * KuhniDSPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuhniDSPRepository extends \Doctrine\ORM\EntityRepository
{
}
