<?php

namespace Kuhni\Bundle\Repository;

/**
 * KuhniKeysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuhniKeysRepository extends \Doctrine\ORM\EntityRepository
{
}
