<?php

namespace Kuhni\Bundle\Repository;

/**
 * KuhniPlasticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuhniPlasticRepository extends \Doctrine\ORM\EntityRepository
{
}
