<?php

namespace Kuhni\Bundle\Repository;

/**
 * ProjectImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
