<?php

namespace Kuhni\Bundle\Repository;

/**
 * RequestCallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestCallRepository extends \Doctrine\ORM\EntityRepository
{
}
