<?php

namespace Kuhni\Bundle\Repository;

/**
 * SalonImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalonImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
