<?php

namespace Kuhni\Bundle\Repository;

/**
 * StationMoscowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationMoscowRepository extends \Doctrine\ORM\EntityRepository
{
}
