<?php

namespace Kuhni\Bundle\Repository;

/**
 * ZayavkaRazmerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZayavkaRazmerRepository extends \Doctrine\ORM\EntityRepository
{
}
