<?php

namespace Kuhni\Bundle\Repository;

/**
 * ZovZakazStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZovZakazStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
