<?php

namespace Kuhni\Bundle\Repository;

/**
 * ZovZakazRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZovZakazRepository extends \Doctrine\ORM\EntityRepository
{
}
